# Copyright 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

version: '2.1'

services:
  
  simplewallet-processor:
    container_name: simplewallet-processor
    build:
      context: .
      dockerfile: ./processor/pyprocessor/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    depends_on:
      - validator
    volumes:
      - '.:/project/Core/'

  simplewallet-client:
    container_name: simplewallet-client
    build:
      context: .
      dockerfile: ./transaction_creation/pyclient/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    environment:
      - 'http_proxy=${http_proxy}'
      - 'https_proxy=${https_proxy}'
      - 'no_proxy=rest-api,validator,${no_proxy}'
    volumes:
      - '.:/project/Core/'
    ports:
      - '0.0.0.0:3000:3000'
    depends_on:
      - sawtooth-rest-api
    entrypoint: "bash -c \"sawtooth keygen --force sawtooth && tail -f /dev/null\""
    stop_signal: SIGKILL

  market-shell:
      build:
        context: .
        dockerfile: ./dev_env/Dockerfile
        args:
          - http_proxy
          - https_proxy
          - no_proxy
      image: market-dev-env
      container_name: market-shell
      volumes:
        - .:/project/sawtooth-marketplace
        - /project/sawtooth-marketplace/sawbuck_app/node_modules
      command: |
        bash -c "
          market-protogen &&
          cd sawbuck_app/ &&
          npm run build &&
          cd ../ &&
          tail -f /dev/null
        "


  market-processor:
    build:
      context: .
      dockerfile: ./processor/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: market-tp
    container_name: market-processor
    volumes:
      - '.:/project/Core'
    depends_on:
      - market-shell
    command: |
      bash -c "
        sleep 1 &&
        marketplace-tp -v \
          -C tcp://validator:4004
      "

  market-rest-api:
    build:
      context: .
      dockerfile: ./rest_api/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: market-rest-api
    container_name: market-rest-api
    volumes:
      - .:/project/Core
    ports:
      - '8040:8000'
    depends_on:
      - market-shell
      - market-ledger-sync
      - rethink
      - validator
    command: |
      bash -c "
        sleep 3 &&
        marketplace-rest-api \
          --host market-rest-api \
          --db-host rethink \
          --validator tcp://validator:4004
      "

  market-ledger-sync:
    build:
      context: .
      dockerfile: ./ledger_sync/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: market-ledger-sync
    container_name: market-ledger-sync
    volumes:
      - .:/project/Core
    depends_on:
      - market-shell
      - rethink
      - validator
    command: |
      bash -c "
        sleep 1 &&
        market-setup-db --host rethink &&
        marketplace-ledger-sync -vv \
          --db-host rethink \
          --validator tcp://validator:4004
      "


  sawtooth-rest-api:
    image: hyperledger/sawtooth-rest-api:1.0
    container_name: sawtooth-rest-api
    expose:
      - 8008
    ports:
      - '8043:8008'
    depends_on:
      - validator
    entrypoint: |
      sawtooth-rest-api -vv
        --connect tcp://validator:4004
        --bind sawtooth-rest-api:8008



  sawtooth-shell:
    image: hyperledger/sawtooth-shell:1.0
    container_name: sawtooth-shell
    volumes:
      - '.:/project/Core'
    working_dir: /project/Core
    container_name: sawtooth-shell
    depends_on:
      - sawtooth-rest-api
    entrypoint: |
      bash -c "
        if [ ! -f /root/.sawtooth/keys/root.priv ]; then
        sawtooth keygen
        fi;
        tail -f /dev/null
      "


  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.0
    container_name: sawtooth-settings-tp
    depends_on:
      - validator
    command: settings-tp -vv --connect tcp://validator:4004


  validator:
    image: hyperledger/sawtooth-validator:1.0
    container_name: sawtooth-validator
    expose:
      - 4004
      - 8800
    ports:
      - '4040:4004'
      - '8800:8800'
    command: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
        sawadm keygen &&
        sawtooth keygen my_key &&
        sawset genesis -k /root/.sawtooth/keys/my_key.priv &&
        sawadm genesis config-genesis.batch
        fi;
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800
      "

  poet-engine:
    image: hyperledger/sawtooth-poet-engine:1.0
    container_name: sawtooth-poet-engine
    volumes:
      - poet-shared:/poet-shared
    command: "bash -c \"\
        while [ ! -f /poet-shared/validator/keys/validator.priv ]; do sleep 1; done && \
        cp -a /poet-shared/validator/keys /etc/sawtooth && \
        poet-engine -C tcp://validator:5050 --component tcp://validator:4004 \
    \""


  poet-validator-registry-tp:
    image: hyperledger/sawtooth-poet-validator-registry-tp:1.0
    container_name: sawtooth-poet-validator-registry-tp
    expose:
      - 4004
    command: poet-validator-registry-tp -C tcp://validator:4004
    environment:
      PYTHONPATH: /project/sawtooth-core/consensus/poet/common
    stop_signal: SIGKILL

