# Copyright 2017 Intel Corpora#   Copyright (c) 2019 Neel Network

#   Permission is hereby granted, free of charge, to any person obtaining a copy
#   of this software and associated documentation files (the "Software"), to deal
#   in the Software without restriction, including without limitation the rights
#   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#   copies of the Software, and to permit persons to whom the Software is
#   furnished to do so, subject to the following conditions:

#   The above copyright notice and this permission notice shall be included in all
#   copies or substantial portions of the Software.

#   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#   SOFTWARE.
#   --------------------------------------------------------------------------

version: '2.1'

services:
  market-processor:
    build:
      context: ../..
      dockerfile: ./processor/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - '../..:/project/sawtooth-marketplace'
    command: marketplace-tp -vv -C tcp://validator:4004

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.0
    depends_on:
      - validator
    command: settings-tp -vv --connect tcp://validator:4004

  validator:
    image: hyperledger/sawtooth-validator:1.0
    expose:
      - 4004
    command: |
      bash -c "
        sawadm keygen &&
        sawtooth keygen my_key &&
        sawset genesis -k /root/.sawtooth/keys/my_key.priv &&
        sawadm genesis config-genesis.batch &&
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800
      "

  rest-api:
    image: hyperledger/sawtooth-rest-api:1.0
    entrypoint: sawtooth-rest-api -vv --connect tcp://validator:4004 --bind rest-api:8008

  test-runner:
    build:
      context: ../../
      dockerfile: ./dev_env/Dockerfile
    volumes:
      - '../../:/project/sawtooth-marketplace'
    command: bash -c "cd integration_tests/blockchain && python3 -m nose2 -v blockchain_integration_test"
    environment:
      PYTHONPATH: /project/sawtooth-marketplace/addressing:/project/sawtooth-marketplace/transaction_creation
